-- MySQL Script generated by MySQL Workbench
-- 05/15/20 15:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Materia` ;

CREATE TABLE IF NOT EXISTS `Materia` (
  `mat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mat_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mat_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignatura` ;

CREATE TABLE IF NOT EXISTS `Asignatura` (
  `asi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `asi_nombre` VARCHAR(45) NOT NULL,
  `mat_id` INT(11) NOT NULL,
  `asi_rotativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`asi_id`, `mat_id`),
  INDEX `fk_Asignatura_Materias` (`mat_id` ASC),
  CONSTRAINT `fk_Asignatura_Materias`
    FOREIGN KEY (`mat_id`)
    REFERENCES `Materia` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `cur_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cur_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cur_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grado` ;

CREATE TABLE IF NOT EXISTS `Grado` (
  `gra_id` INT(11) NOT NULL AUTO_INCREMENT,
  `gra_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gra_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Curso_has_Grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso_has_Grado` ;

CREATE TABLE IF NOT EXISTS `Curso_has_Grado` (
  `cur_gra_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cur_id` INT(11) NOT NULL,
  `gra_id` INT(11) NOT NULL,
  PRIMARY KEY (`cur_gra_id`, `cur_id`, `gra_id`),
  INDEX `fk_Curso_has_Grado_Curso1` (`cur_id` ASC),
  INDEX `fk_Curso_has_Grado_Grado1` (`gra_id` ASC),
  CONSTRAINT `fk_Curso_has_Grado_Curso1`
    FOREIGN KEY (`cur_id`)
    REFERENCES `Curso` (`cur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Grado_Grado1`
    FOREIGN KEY (`gra_id`)
    REFERENCES `Grado` (`gra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Grado_has_Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Grado_has_Asignatura` ;

CREATE TABLE IF NOT EXISTS `Grado_has_Asignatura` (
  `gra_asi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `gra_id` INT(11) NOT NULL,
  `asi_id` INT(11) NOT NULL,
  PRIMARY KEY (`gra_asi_id`, `gra_id`, `asi_id`),
  INDEX `fk_Grado_has_Asignatura_Grado1` (`gra_id` ASC),
  INDEX `fk_Grado_has_Asignatura_Asignatura1` (`asi_id` ASC),
  CONSTRAINT `fk_Grado_has_Asignatura_Asignatura1`
    FOREIGN KEY (`asi_id`)
    REFERENCES `Asignatura` (`asi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grado_has_Asignatura_Grado1`
    FOREIGN KEY (`gra_id`)
    REFERENCES `Grado` (`gra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Indicador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Indicador` ;

CREATE TABLE IF NOT EXISTS `Indicador` (
  `ind_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ind_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ano` ;

CREATE TABLE IF NOT EXISTS `Ano` (
  `ano_id` INT NOT NULL AUTO_INCREMENT,
  `ano_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ano_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Periodo` ;

CREATE TABLE IF NOT EXISTS `Periodo` (
  `per_id` INT NOT NULL,
  `per_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ano_has_Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ano_has_Periodo` ;

CREATE TABLE IF NOT EXISTS `Ano_has_Periodo` (
  `ano_per_id` INT NOT NULL AUTO_INCREMENT,
  `per_id` INT NOT NULL,
  `ano_id` INT NOT NULL,
  PRIMARY KEY (`ano_per_id`, `per_id`, `ano_id`),
  INDEX `fk_Ano_has_Periodo_Periodo1_idx` (`per_id` ASC),
  INDEX `fk_Ano_has_Periodo_Ano1_idx` (`ano_id` ASC),
  CONSTRAINT `fk_Ano_has_Periodo_Ano1`
    FOREIGN KEY (`ano_id`)
    REFERENCES `Ano` (`ano_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ano_has_Periodo_Periodo1`
    FOREIGN KEY (`per_id`)
    REFERENCES `Periodo` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona` ;

CREATE TABLE IF NOT EXISTS `Persona` (
  `per_id` INT NOT NULL AUTO_INCREMENT,
  `per_nombre` VARCHAR(45) NOT NULL,
  `per_apellido` VARCHAR(45) NOT NULL,
  `per_identificacion` VARCHAR(45) NOT NULL,
  `per_telefono` INT NULL,
  `per_celular` INT NULL,
  `per_correo` VARCHAR(45) NULL,
  `per_codigo` INT NOT NULL,
  `per_direccion` VARCHAR(45) NULL,
  `per_pais` VARCHAR(45) NOT NULL,
  `per_ciudad` VARCHAR(45) NOT NULL,
  `per_nacimiento` VARCHAR(45) NOT NULL,
  `per_ingreso` INT NULL,
  `per_grado` INT NOT NULL,
  `per_contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cargo` ;

CREATE TABLE IF NOT EXISTS `Cargo` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `car_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona_has_Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona_has_Cargo` ;

CREATE TABLE IF NOT EXISTS `Persona_has_Cargo` (
  `per_car_id` INT NOT NULL AUTO_INCREMENT,
  `per_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `per_fam_id` INT NULL,
  PRIMARY KEY (`per_car_id`, `per_id`, `car_id`, `per_fam_id`),
  INDEX `fk_Persona_has_Cargo_Cargo1_idx` (`car_id` ASC),
  INDEX `fk_Persona_has_Cargo_Persona1_idx` (`per_id` ASC),
  INDEX `fk_Persona_has_Cargo_Persona2_idx` (`per_fam_id` ASC),
  CONSTRAINT `fk_Persona_has_Cargo_Persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `Persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Cargo_Cargo1`
    FOREIGN KEY (`car_id`)
    REFERENCES `Cargo` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Cargo_Persona2`
    FOREIGN KEY (`per_fam_id`)
    REFERENCES `Persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Permiso` ;

CREATE TABLE IF NOT EXISTS `Permiso` (
  `perm_id` INT NOT NULL AUTO_INCREMENT,
  `perm_nom` VARCHAR(45) NOT NULL,
  `perm_descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`perm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona_has_Permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona_has_Permiso` ;

CREATE TABLE IF NOT EXISTS `Persona_has_Permiso` (
  `per_perm_id` INT NOT NULL AUTO_INCREMENT,
  `per_id` INT NOT NULL,
  `perm_id` INT NOT NULL,
  `per_perm_estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`per_perm_id`, `per_id`, `perm_id`),
  INDEX `fk_Persona_has_Permiso_Permiso1_idx` (`perm_id` ASC),
  INDEX `fk_Persona_has_Permiso_Persona1_idx` (`per_id` ASC),
  CONSTRAINT `fk_Persona_has_Permiso_Persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `Persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Permiso_Permiso1`
    FOREIGN KEY (`perm_id`)
    REFERENCES `Permiso` (`perm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona_has_Asignatura_has_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona_has_Asignatura_has_Curso` ;

CREATE TABLE IF NOT EXISTS `Persona_has_Asignatura_has_Curso` (
  `per_asi_cur_id` INT NOT NULL AUTO_INCREMENT,
  `per_id` INT NOT NULL,
  `cur_gra_id` INT(11) NOT NULL,
  `asi_id` INT(11) NOT NULL,
  `ano_per_id` INT NOT NULL,
  `per_asig_curso_rotativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`per_asi_cur_id`, `per_id`, `cur_gra_id`, `asi_id`, `ano_per_id`),
  INDEX `fk_Persona_has_Asignatura_has_Curso_Persona1_idx` (`per_id` ASC),
  INDEX `fk_Persona_has_Asignatura_has_Curso_Curso_has_Grado1_idx` (`cur_gra_id` ASC),
  INDEX `fk_Persona_has_Asignatura_has_Curso_Asignatura1_idx` (`asi_id` ASC),
  INDEX `fk_Persona_has_Asignatura_has_Curso_Ano_has_Periodo1_idx` (`ano_per_id` ASC),
  CONSTRAINT `fk_Persona_has_Asignatura_has_Curso_Persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `Persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Asignatura_has_Curso_Curso_has_Grado1`
    FOREIGN KEY (`cur_gra_id`)
    REFERENCES `Curso_has_Grado` (`cur_gra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Asignatura_has_Curso_Asignatura1`
    FOREIGN KEY (`asi_id`)
    REFERENCES `Asignatura` (`asi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Asignatura_has_Curso_Ano_has_Periodo1`
    FOREIGN KEY (`ano_per_id`)
    REFERENCES `Ano_has_Periodo` (`ano_per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matricula` ;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `matr_id` INT NOT NULL AUTO_INCREMENT,
  `cur_gra_id` INT(11) NOT NULL,
  `per_id` INT NOT NULL,
  `ano_per_id` INT NOT NULL,
  `matr_fecha` VARCHAR(45) NOT NULL,
  `matr_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matr_id`, `cur_gra_id`, `per_id`, `ano_per_id`),
  INDEX `fk_Matricula_Curso_has_Grado1_idx` (`cur_gra_id` ASC),
  INDEX `fk_Matricula_Persona1_idx` (`per_id` ASC),
  INDEX `fk_Matricula_Ano_has_Periodo1_idx` (`ano_per_id` ASC),
  CONSTRAINT `fk_Matricula_Curso_has_Grado1`
    FOREIGN KEY (`cur_gra_id`)
    REFERENCES `Curso_has_Grado` (`cur_gra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Persona1`
    FOREIGN KEY (`per_id`)
    REFERENCES `Persona` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Ano_has_Periodo1`
    FOREIGN KEY (`ano_per_id`)
    REFERENCES `Ano_has_Periodo` (`ano_per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
